apiVersion: v2
name: cluster-autoscaler-app-bundle
description: A Helm chart for Cluster Autoscaler with IAM resources
version: 1.34.1-1
appVersion: 1.34.1
home: https://github.com/giantswarm/cluster-autoscaler-app
icon: https://s.giantswarm.io/app-icons/k8s-initiator/1/dark.svg
kubeVersion: ">=1.17.0-0"
sources:
  - https://github.com/giantswarm/cluster-autoscaler-app
annotations:
  application.giantswarm.io/team: tenet
  ui.giantswarm.io/logo: https://s.giantswarm.io/app-icons/k8s-initiator/1/dark.svg
