apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-autoscaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-autoscaler.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.clusterID }}-cluster-autoscaler"
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
