apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-autoscaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-autoscaler.labels" . | nindent 4 }}
  {{- if or (eq .Values.provider "capa") .Values.serviceAccount.annotations }}
  annotations:
    {{- if eq .Values.provider "capa" }}
    eks.amazonaws.com/role-arn: "{{ .Values.clusterID }}-cluster-autoscaler"
    {{- end }}
    {{- if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
