apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-autoscaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-autoscaler.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.clusterID }}-cluster-autoscaler-role
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
