apiVersion: v2
name: cluster-autoscaler-app
description: A Helm chart for the Cluster Autoscaler.
version: 1.34.3-1
appVersion: 1.34.3
home: https://github.com/giantswarm/cluster-autoscaler-app
icon: https://s.giantswarm.io/app-icons/k8s-initiator/1/dark.svg
annotations:
  application.giantswarm.io/team: turtles
  ui.giantswarm.io/logo: https://s.giantswarm.io/app-icons/k8s-initiator/1/dark.svg
